### ISSUE TITLE
About TransposonDB.fasta

### ISSUE THREAD

**Issue by unavailable-2374** [DerKevinRiehl/TransposonUltimate#1]
I didn't find any parameter related to this, how can I use it.thanks.

**Comment by DerKevinRiehl** [comment]
Dear unavailable-2374,
thank you very much for your interest in our work.

Could you please be a little more specific in your question?
Do you want to use it in the context of classification (tool [rfsb](https://github.com/DerKevinRiehl/transposon_classifier_rfsb)), annotation (tool [reasonaTE](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE)), or detection (tool [deTEct](https://github.com/DerKevinRiehl/transposition_detector_deTEct))?
What exactly do you want to do with it? 

In general, TransposonDB.fasta is a fasta file, so there are no parameters necessary, its just a file consisting of DNA sequences of known transposons. This FASTA file was used to train our RFSB classifier module. You can find the TransposonDB.fasta [here](https://zenodo.org/record/5518085#.YieU0ZYxmUk) in the classification.zip folder.

Thank you very much for your answer,
Best regards,
Kevin Riehl

**Comment by unavailable-2374** [comment]
Dear Kevin Riehl
I am so happy to get your response.

I thought TransposonDB.fasta is a database that using for the whole analysis  about identification TE.

thank you for your answer,
Best regards,
Shuo Cao

**Comment by DerKevinRiehl** [comment]
Dear Shuo Cao,
happy to help. If you have any further questions or ideas please let me know.

Best, Kevin
