### ISSUE TITLE
For some software, can they run with more thread?

### ISSUE THREAD

**Issue by Djangodu** [DerKevinRiehl/TransposonUltimate#11]
Dear Kevin

​For example, when I ran my 3.0GB genome sequence with must and mitetracker, using only 10 and 4 threads respectively, it took 50 hours, but no work was done. 

​While the classical work will start, after they run with must and mitetracker, the research work will take more and more time with just 4 threads, which is shown in the command line while running.

So, can you come up with some sort of solution to this?

Looking forward to your reply
Sincerely yours

**Comment by DerKevinRiehl** [comment]
Der Djangodu,
I was just wrapping these tools mitetracker and must in a pipeline so people can easily use it without having the pain to install them by themselves (as there was few to none manuals), but I didnt develop these tools and I am not their author.

If some tools take long, you might consider not using all of them.
Best, Kevin

**Comment by Djangodu** [comment]
Dear Kevin

​Thank you very much for your patient responses to my questions, these suggestions are very important to me.

Best wish
Sincerely yours
