### ISSUE TITLE
Repeatmasker and Repeatmodeler Install

### ISSUE THREAD

**Issue by roperete** [DerKevinRiehl/TransposonUltimate#2]
As stated in the readme notes, RepeatMasker and RepeatModeler give trouble when installed from conda.

It was also my case, by using 

conda install -c bioconda repeatmasker
and
conda install -c bioconda repeatmodeler

Simply adding conda-forge as a source did the trick for me, thus:

conda install -c bioconda -c conda-forge repeatmasker
and
conda install -c bioconda -c conda-forge repeatmodeler 

I hope this is useful for somebody else!

**Comment by mhemberg** [comment]
Thanks for reporting this!
